set(CMAKE_SYSTEM_NAME QNX)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()
set(QNX_PATH /opt/qnx710 CACHE STRING "QNX path")
set(CMAKE_FIND_ROOT_PATH  ${QNX_PATH}/target/qnx7/aarch64le/usr)
set(CMAKE_CXX_COMPILER ${QNX_PATH}/host/linux/x86_64/usr/bin/ntoaarch64-g++)
set(CMAKE_C_COMPILER  ${QNX_PATH}/host/linux/x86_64/usr/bin/ntoaarch64-gcc)
#set(CMAKE_C_FLAGS "-Vgcc_ntoaarch64le")
#set(CMAKE_CXX_FLAGS "-Vgcc_ntoaarch64le")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_QNX_SOURCE")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_QNX_SOURCE -I/opt/qnx710/target/qnx7/usr/include")
